// Mock fallback data for the APL T20 Admin Portal
// Used ONLY in development mode when the real API is unavailable or returns an error

// Mock auth is ONLY active in DEV builds.
// VITE_ENABLE_MOCK_AUTH is intentionally ignored in production to prevent
// accidental staging configs from enabling mock login on the live site.
export const IS_MOCK_AUTH_ENABLED = import.meta.env.DEV === true
  && import.meta.env.VITE_ENABLE_MOCK_AUTH === 'true'

// All mock credentials are sourced exclusively from environment variables.
// No hardcoded fallback strings — if env vars are absent, mock auth is unavailable.
export const MOCK_TOKEN = IS_MOCK_AUTH_ENABLED ? (import.meta.env.VITE_MOCK_ADMIN_TOKEN ?? '') : ''
export const MOCK_EMAIL = IS_MOCK_AUTH_ENABLED ? (import.meta.env.VITE_MOCK_ADMIN_EMAIL ?? '') : ''
export const MOCK_PASSWORD = IS_MOCK_AUTH_ENABLED ? (import.meta.env.VITE_MOCK_ADMIN_PASSWORD ?? '') : ''

export const MOCK_REGISTRATIONS = [
  {
    id: 1,
    registration_code: 'APL-MN2024',
    full_name: 'Mohammad Nabi',
    email: 'mnabi@cricket.af',
    phone: '+93 700 123456',
    dob: '1985-01-01',
    city: 'Kabul',
    nationality: 'Afghanistan',
    country_of_residence: 'Afghanistan',
    representing_country: 'Afghanistan',
    passport_number: 'AF1234567',
    player_category: 'Platinum',
    playing_role: 'All Rounder (Bowling)',
    batting_hand: 'Right-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Off-break',
    player_status: 'Afghanistan (National)',
    player_availability: 'Available for full season',
    twtenty_matches_count: 187,
    previous_teams: 'Kabul Eagles, Nangarhar Leopards',
    profile_link: 'https://www.espncricinfo.com/cricketers/mohammad-nabi-311911',
    playing_experience: 'Afghanistan national captain and veteran T20 all-rounder.',
    status: 'approved',
    created_at: '2026-07-15T09:30:00Z',
    agent_full_name: 'Bilal Rahimi',
    agent_company_name: 'Cricket First Agency',
    agent_phone_number: '+971 50 1234567',
    agent_email_address: 'bilal@cricketfirst.ae',
    passport_url: 'https://api-staging.chaptersquare.com/uploads/images/passport_sample.jpg',
    action_shot_url: 'https://api-staging.chaptersquare.com/uploads/images/action_sample.jpg',
    photo_url: 'https://api-staging.chaptersquare.com/uploads/images/headshot_sample.jpg',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: true,
    accept_relegation: false,
    relegation_category: '',
    relegation_limit: 'None',
    consider_icon_player: 'yes',
  },
  {
    id: 2,
    registration_code: 'APL-RG5501',
    full_name: 'Rashid Khan',
    email: 'rashid@cricket.af',
    phone: '+93 700 654321',
    dob: '1998-09-20',
    city: 'Nangarhar',
    nationality: 'Afghanistan',
    country_of_residence: 'UAE',
    representing_country: 'Afghanistan',
    passport_number: 'AF7654321',
    player_category: 'Platinum',
    playing_role: 'Bowler',
    batting_hand: 'Left-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Leg-spin',
    player_status: 'Afghanistan (National)',
    player_availability: 'Subject to national-team commitments',
    twtenty_matches_count: 302,
    previous_teams: 'Sunrisers Hyderabad, Adelaide Strikers, Trent Rockets',
    profile_link: 'https://www.espncricinfo.com/cricketers/rashid-khan-793463',
    playing_experience: 'World-class leg-spin bowler and global T20 franchise star.',
    status: 'approved',
    created_at: '2026-07-16T10:00:00Z',
    agent_full_name: '',
    agent_company_name: '',
    agent_phone_number: '',
    agent_email_address: '',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: true,
    accept_relegation: false,
    relegation_category: '',
    relegation_limit: 'None',
    consider_icon_player: 'yes',
  },
  {
    id: 3,
    registration_code: 'APL-AZ9902',
    full_name: 'Babar Azam',
    email: 'babar.azam@cricket.pk',
    phone: '+92 300 9988776',
    dob: '1994-10-15',
    city: 'Lahore',
    nationality: 'Pakistan',
    country_of_residence: 'Pakistan',
    representing_country: 'Pakistan',
    passport_number: 'PK8765432',
    player_category: 'Diamond',
    playing_role: 'Batter',
    batting_hand: 'Right-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Off-break',
    player_status: 'Overseas (National)',
    player_availability: 'Available for selected dates',
    twtenty_matches_count: 119,
    previous_teams: 'Karachi Kings, Somerset',
    profile_link: 'https://www.espncricinfo.com/cricketers/babar-azam-348144',
    playing_experience: 'ICC Men\'s T20I ranked batter.',
    status: 'pending',
    created_at: '2026-07-20T14:25:00Z',
    agent_full_name: 'Talha Sheikh',
    agent_company_name: 'Prime Sports Management',
    agent_phone_number: '+92 321 5678901',
    agent_email_address: 'talha@primesports.pk',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: true,
    relegation_category: 'Gold',
    relegation_limit: 'Gold',
    consider_icon_player: 'no',
  },
  {
    id: 4,
    registration_code: 'APL-SK1183',
    full_name: 'Shakib Al Hasan',
    email: 'shakib@cricket.bd',
    phone: '+880 1700 000001',
    dob: '1987-03-24',
    city: 'Dhaka',
    nationality: 'Bangladesh',
    country_of_residence: 'Bangladesh',
    representing_country: 'Bangladesh',
    passport_number: 'BD1122334',
    player_category: 'Diamond',
    playing_role: 'All Rounder (Bowling)',
    batting_hand: 'Left-hand bat',
    bowling_arm: 'Left-arm',
    bowling_type: 'Slow left-arm orthodox',
    player_status: 'Overseas (National)',
    player_availability: 'Subject to national-team commitments',
    twtenty_matches_count: 128,
    previous_teams: 'Kolkata Knight Riders, Dhaka Dynamites',
    profile_link: 'https://www.espncricinfo.com/cricketers/shakib-al-hasan-56143',
    playing_experience: 'ICC World all-rounder and Bangladesh national team star.',
    status: 'under_review',
    created_at: '2026-07-22T09:15:00Z',
    agent_full_name: 'Arif Rahman',
    agent_company_name: 'Sport Circle BD',
    agent_phone_number: '+880 1711 999888',
    agent_email_address: 'arif@sportcircle.bd',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: true,
    relegation_category: 'Silver',
    relegation_limit: 'Silver',
    consider_icon_player: 'no',
  },
  {
    id: 5,
    registration_code: 'APL-LN7744',
    full_name: 'Noor Ahmad',
    email: 'noorahmad@cricket.af',
    phone: '+93 700 112233',
    dob: '2003-01-10',
    city: 'Kandahar',
    nationality: 'Afghanistan',
    country_of_residence: 'Afghanistan',
    representing_country: 'Afghanistan',
    passport_number: 'AF4455667',
    player_category: 'Gold',
    playing_role: 'Bowler',
    batting_hand: 'Left-hand bat',
    bowling_arm: 'Left-arm',
    bowling_type: 'Chinaman',
    player_status: 'Afghanistan (Domestic)',
    player_availability: 'Available for full season',
    twtenty_matches_count: 72,
    previous_teams: 'Kabul Eagles, Bost Defenders',
    profile_link: '',
    playing_experience: 'Rising star domestic spinner.',
    status: 'pending',
    created_at: '2026-07-25T11:40:00Z',
    agent_full_name: '',
    agent_company_name: '',
    agent_phone_number: '',
    agent_email_address: '',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: true,
    relegation_category: 'Silver',
    relegation_limit: 'Silver',
    consider_icon_player: 'no',
  },
  {
    id: 6,
    registration_code: 'APL-AR3327',
    full_name: 'Azmatullah Omarzai',
    email: 'azmat@cricket.af',
    phone: '+93 700 778899',
    dob: '2001-05-06',
    city: 'Khost',
    nationality: 'Afghanistan',
    country_of_residence: 'Afghanistan',
    representing_country: 'Afghanistan',
    passport_number: 'AF9988112',
    player_category: 'Gold',
    playing_role: 'All Rounder (Batting)',
    batting_hand: 'Right-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Medium-fast',
    player_status: 'Afghanistan (National)',
    player_availability: 'Available for full season',
    twtenty_matches_count: 45,
    previous_teams: 'Balkh Legends, Nangarhar Leopards',
    profile_link: '',
    playing_experience: 'Dynamic batting all-rounder for the Afghan national team.',
    status: 'approved',
    created_at: '2026-07-28T08:50:00Z',
    agent_full_name: '',
    agent_company_name: '',
    agent_phone_number: '',
    agent_email_address: '',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: false,
    relegation_category: '',
    relegation_limit: 'None',
    consider_icon_player: 'no',
  },
  {
    id: 7,
    registration_code: 'APL-TM6619',
    full_name: 'Tim Southee',
    email: 'tim.southee@cricket.nz',
    phone: '+64 21 555 4444',
    dob: '1988-12-11',
    city: 'Auckland',
    nationality: 'New Zealand',
    country_of_residence: 'New Zealand',
    representing_country: 'New Zealand',
    passport_number: 'NZ6655443',
    player_category: 'Silver',
    playing_role: 'Bowler',
    batting_hand: 'Right-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Medium-fast',
    player_status: 'Overseas (National)',
    player_availability: 'Subject to club or franchise release',
    twtenty_matches_count: 100,
    previous_teams: 'Mumbai Indians, Northern Brave',
    profile_link: '',
    playing_experience: 'New Zealand seam bowling stalwart.',
    status: 'rejected',
    created_at: '2026-08-01T13:30:00Z',
    agent_full_name: 'James Court',
    agent_company_name: 'Southern Hemisphere Sports',
    agent_phone_number: '+64 9 999 8888',
    agent_email_address: 'james@shsports.nz',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: true,
    relegation_category: 'Silver',
    relegation_limit: 'Silver',
    consider_icon_player: 'no',
  },
  {
    id: 8,
    registration_code: 'APL-IK8801',
    full_name: 'Ibrahim Zadran',
    email: 'ibrahim@cricket.af',
    phone: '+93 700 443322',
    dob: '2000-07-25',
    city: 'Kabul',
    nationality: 'Afghanistan',
    country_of_residence: 'UAE',
    representing_country: 'Afghanistan',
    passport_number: 'AF2233445',
    player_category: 'Emerging',
    playing_role: 'Batter',
    batting_hand: 'Right-hand bat',
    bowling_arm: 'Right-arm',
    bowling_type: 'Off-break',
    player_status: 'Emerging Player (Domestic)',
    player_availability: 'Available for full season',
    twtenty_matches_count: 31,
    previous_teams: 'Kabul Eagles',
    profile_link: '',
    playing_experience: 'Emerging top-order batter with strong domestic record.',
    status: 'pending',
    created_at: '2026-08-05T16:10:00Z',
    agent_full_name: '',
    agent_company_name: '',
    agent_phone_number: '',
    agent_email_address: '',
    passport_url: '',
    action_shot_url: '',
    photo_url: '',
    right_profile_url: '',
    left_profile_url: '',
    icon_player_nomination: false,
    accept_relegation: false,
    relegation_category: '',
    relegation_limit: 'None',
    consider_icon_player: 'no',
  },
]

export const MOCK_TEAMS = [
  {
    id: 1,
    name: 'Kabul Eagles',
    slug: 'kabul-eagles',
    city: 'Kabul',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/action_sample.jpg',
    primary_color: '#0575E6',
    home_venue: 'Kabul International Cricket Stadium',
    description: 'The premier franchise representing the capital city Kabul.'
  },
  {
    id: 2,
    name: 'Nangarhar Leopards',
    slug: 'nangarhar-leopards',
    city: 'Jalalabad',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/headshot_sample.jpg',
    primary_color: '#d97706',
    home_venue: 'Ghazi Amanullah Khan International Cricket Stadium',
    description: 'Dynamic powerhouses representing Nangarhar province.'
  },
  {
    id: 3,
    name: 'Balkh Legends',
    slug: 'balkh-legends',
    city: 'Mazar-i-Sharif',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/action_sample.jpg',
    primary_color: '#10b981',
    home_venue: 'Balkh Cricket Stadium',
    description: 'Former champions known for explosive top-order batting.'
  },
  {
    id: 4,
    name: 'Kandahar Knights',
    slug: 'kandahar-knights',
    city: 'Kandahar',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/passport_sample.jpg',
    primary_color: '#8b5cf6',
    home_venue: 'Kandahar International Cricket Stadium',
    description: 'Fierce competitor representing Southern Afghanistan.'
  },
  {
    id: 5,
    name: 'Paktia Panthers',
    slug: 'paktia-panthers',
    city: 'Khost',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/headshot_sample.jpg',
    primary_color: '#ef4444',
    home_venue: 'Khost Cricket Stadium',
    description: 'Aggressive pace battery representing the Eastern Zone.'
  }
]

export const MOCK_SPONSORS = [
  {
    id: 1,
    name: 'Red Bull',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/headshot_sample.jpg',
    tier: 'official_partner',
    website_url: 'https://redbull.com',
    display_order: 1,
    is_active: true
  },
  {
    id: 2,
    name: 'Kam Air',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/action_sample.jpg',
    tier: 'title_sponsor',
    website_url: 'https://flykamair.com',
    display_order: 2,
    is_active: true
  },
  {
    id: 3,
    name: 'Etisalat Afghanistan',
    logo_url: 'https://api-staging.chaptersquare.com/uploads/images/passport_sample.jpg',
    tier: 'gold_sponsor',
    website_url: 'https://etisalat.af',
    display_order: 3,
    is_active: true
  }
]

